import Link from "next/link";

export default function Footer() {
  return (
    <footer className="border-t border-border-soft">
      <div className="mx-auto max-w-6xl px-6 py-10">
        <div className="flex flex-col gap-6 md:flex-row md:items-center md:justify-between">
          <p className="max-w-md text-[13px] leading-relaxed text-text-faint">
            TradeIQ signals are generated by rule-based technical analysis.
            Nothing here is financial advice. Trading forex carries substantial
            risk of loss — never risk money you can&apos;t afford to lose.
          </p>
          <div className="flex gap-6 text-[13px] text-text-muted">
            <Link href="/signals" className="hover:text-text">
              Signal history
            </Link>
            <Link href="/login" className="hover:text-text">
              Log in
            </Link>
          </div>
        </div>
        <p className="mt-8 text-[12px] text-text-faint">
          © {new Date().getFullYear()} TradeIQ.
        </p>
      </div>
    </footer>
  );
}
